compile:
	g++ pthread_fifo_demo.cpp -o pthread_fifo_demo -pthread
run:
	./pthread_fifo_demo
cr:
	g++ pthread_fifo_demo.cpp -o pthread_fifo_demo -pthread; ./pthread_fifo_demo
clean:
	rm -f a.out pthread_fifo_demo